"""add_indexes_for_todo_performance

Revision ID: d96cbbf8b617
Revises: a0790c76a129
Create Date: 2026-09-16 21:36:00.221490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96cbbf8b617'
down_revision: Union[str, None] = 'a0790c76a129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Composite index for user-filtered todo queries with ordering
    # Supports: WHERE user_id = ? ORDER BY created_at DESC, id DESC LIMIT ?
    op.create_index(
        'ix_todos_user_id_created_at_id_desc',
        'todos',
        ['user_id', 'created_at', 'id'],
        postgresql_using='btree',
        postgresql_ops={'created_at': 'DESC', 'id': 'DESC'},
    )

    # Index for counting todos by user
    op.create_index(
        'ix_todos_user_id',
        'todos',
        ['user_id'],
        postgresql_using='btree',
    )

    # Index on users.email for user lookup by email
    op.create_index(
        'ix_users_email',
        'users',
        ['email'],
        unique=True,
        postgresql_using='btree',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_user_id_created_at_id_desc', table_name='todos')
    op.drop_index('ix_todos_user_id', table_name='todos')
    op.drop_index('ix_users_email', table_name='users')
    # ### end Alembic commands ###
